/**
 * Definierar en global array med artistobjekt som används för att rendera korten och spelschemat.
 * Varje objekt har:
 * – name, style, desc, time, genre, floor, img
 * – social.spotify (URL), social.instagram (handle utan @)
 * – track (embed-URL till ett representativt spår)
 * – pressImage (väg till pressbild)
 * – spotifyEmbed (embed-URL till artistprofil)
 * – ticketLink (länk till biljett)
 */
const artistsData = [
  {
    name: "Julius",
    style: "Afro house med Keinemusik-vibbar, perfekt för förfesten.",
    desc: "Afro house / Keinemusik på TG.",
    time: "21:00–22:00",
    genre: "Afro house / Keinemusik",
    floor: "Teatergatans uteservering",
    img: "https://via.placeholder.com/350x200?text=Julius",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_JULIUS",
      instagram: "julius.dj",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_JULIUS",
    pressImage: "assets/press/julius.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_JULIUS",
  },
  {
    name: "Linnea Alfons",
    style: "Afro house med Keinemusik-vibbar, perfekt för förfesten.",
    desc: "Afro house / Keinemusik på TG.",
    time: "22:00–23:00",
    genre: "Afro house / Keinemusik",
    floor: "Teatergatans uteservering",
    img: "https://via.placeholder.com/350x200?text=Linnea+Alfons",
    social: {
      spotify: "#",
      instagram: "#",
    },
    track: "#",
    pressImage: "assets/press/linnea-alfons.jpg",
    spotifyEmbed: "#",
  },
  {
    name: "Kevine",
    style: "Klubbig, global, rytmisk energi med pulserande beats.",
    desc: "Klubbig, global, rytmisk energi i Röda rummet.",
    time: "23:00–00:00",
    genre: "Klubbig, global, rytmisk energi",
    floor: "Röda rummet",
    img: "https://via.placeholder.com/350x200?text=Kevine",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_KEVINE",
      instagram: "kevine.dj",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_KEVINE",
    pressImage: "assets/press/kevine.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_KEVINE",
  },
  {
    name: "Kim Öhman",
    style: "Tung techno med melodiska inslag för sena timmar.",
    desc: "Klubbig, global, rytmisk energi i Röda rummet.",
    time: "00:00–00:55",
    genre: "Klubbig, global, rytmisk energi",
    floor: "Röda rummet",
    img: "https://via.placeholder.com/350x200?text=Kim+%C3%96hman",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_KIM",
      instagram: "kim.ohman",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_KIM",
    pressImage: "assets/press/kim-ohman.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_KIM",
    ticketLink: "#",
  },
  {
    name: "Ingrid Borås",
    style: "Melodisk techno med souliga undertoner.",
    desc: "Hypnotiska beats och atmosfäriska ljudlandskap i Röda rummet.",
    time: "01:10–02:00",
    genre: "Klubbig, global, rytmisk energi",
    floor: "Röda rummet",
    img: "https://via.placeholder.com/350x200?text=Ingrid+Boras",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_INGRID",
      instagram: "ingrid.boras",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_INGRID",
    pressImage: "assets/press/ingrid-boras.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_INGRID",
  },
  {
    name: "Thilly & Kimya",
    style: "Duon levererar hypnotiska beats och atmosfäriska ljudlandskap.",
    desc: "Hypnotiska beats och atmosfäriska ljudlandskap i Röda rummet.",
    time: "02:00–03:00",
    genre: "Klubbig, global, rytmisk energi",
    floor: "Röda rummet",
    img: "https://via.placeholder.com/350x200?text=Thilly+%26+Kimya",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_THILLY",
      instagram: "thillyandkimya",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_THILLY",
    pressImage: "assets/press/thilly-kimya.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_THILLY",
  },
  {
    name: "Milli DJ",
    style: "Experimentellt, mainstream, elektroniskt med dansanta rytmer.",
    desc: "Experimentellt, mainstream, elektroniskt i Övre baren.",
    time: "23:00–00:00",
    genre: "Experimentellt, mainstream, elektroniskt",
    floor: "Övre baren",
    img: "https://via.placeholder.com/350x200?text=Milli+DJ",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_MILLI",
      instagram: "millidj",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_MILLI",
    pressImage: "assets/press/milli-dj.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_MILLI",
  },
  {
    name: "Sara Appeli",
    style: "Experimentellt, mainstream, elektroniskt med dansanta rytmer.",
    desc: "Experimentellt, mainstream, elektroniskt i Övre baren.",
    time: "00:00–01:00",
    genre: "Experimentellt, mainstream, elektroniskt",
    floor: "Övre baren",
    img: "https://via.placeholder.com/350x200?text=Sara+Appeli",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_SARA",
      instagram: "saraappeli",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_SARA",
    pressImage: "assets/press/sara-appeli.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_SARA",
  },
  {
    name: "Danne / Arvid",
    style: "Experimentellt, mainstream, elektroniskt med futuristisk edge.",
    desc: "Experimentellt, mainstream, elektroniskt i Övre baren.",
    time: "01:15–02:00",
    genre: "Experimentellt, mainstream, elektroniskt",
    floor: "Övre baren",
    img: "https://via.placeholder.com/350x200?text=Danne+%2F+Arvid",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_DANNE",
      instagram: "soxcyted",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_DANNE",
    pressImage: "assets/press/danne-soxcyted.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_DANNE",
  },
  {
    name: "Benji Bastae",
    style: "Experimentellt, mainstream, elektroniskt kraftpaket.",
    desc: "Experimentellt, mainstream, elektroniskt i Övre baren.",
    time: "02:00–03:00",
    genre: "Experimentellt, mainstream, elektroniskt",
    floor: "Övre baren",
    img: "https://via.placeholder.com/350x200?text=Benji+Bastae",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_BENJI",
      instagram: "benjibastae",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_BENJI",
    pressImage: "assets/press/benji-bastae.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_BENJI",
  },
  {
    name: "Liv Andersson",
    style: "Afro, baile, R&B, hiphop – lätt, svängig vibe.",
    desc: "Afro, baile, R&B, hiphop i Lilla London.",
    time: "23:00–00:00",
    genre: "Afro, baile, R&B, hiphop",
    floor: "Lilla London",
    img: "https://via.placeholder.com/350x200?text=Liv+Andersson",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_LIV",
      instagram: "livandersson",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_LIV",
    pressImage: "assets/press/liv-andersson.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_LIV",
  },
  {
    name: "Makki",
    style: "Afro, baile, R&B, hiphop – lätt, rytmisk och dansant.",
    desc: "Afro, baile, R&B, hiphop i Lilla London.",
    time: "01:00–02:00",
    genre: "Afro, baile, R&B, hiphop",
    floor: "Lilla London",
    img: "https://via.placeholder.com/350x200?text=Makki",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_MAKKI",
      instagram: "makki.dj",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_MAKKI",
    pressImage: "assets/press/makki.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_MAKKI",
  },
  {
    name: "Kajsa Nyström",
    style: "Afro, baile, R&B, hiphop – lätt vibe med soulkänsla.",
    desc: "Afro, baile, R&B, hiphop i Lilla London.",
    time: "02:00–03:00",
    genre: "Afro, baile, R&B, hiphop",
    floor: "Lilla London",
    img: "https://via.placeholder.com/350x200?text=Kajsa+Nystr%C3%B6m",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_KAJSA",
      instagram: "kajsanystrom",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_KAJSA",
    pressImage: "assets/press/kajsa-nystrom.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_KAJSA",
  },
  {
    name: "Isabbel",
    style: "Blandade uttryck, publikdrag, curerat vibe.",
    desc: "Blandade uttryck, publikdrag på Teatergatan.",
    time: "00:00–01:00",
    genre: "Blandade uttryck, curated vibe",
    floor: "Teatergatan",
    img: "https://via.placeholder.com/350x200?text=Isabbel",
    social: {
      spotify: "#",
      instagram: "isabbel",
    },
    track: "#",
    pressImage: "assets/press/isabbel.jpg",
    spotifyEmbed: "#",
  },
  {
    name: "DJ Schysst",
    style: "Blandade uttryck, publikdrag, curerat vibe.",
    desc: "Blandade uttryck, publikdrag på Teatergatan.",
    time: "01:00–02:00",
    genre: "Blandade uttryck, curated vibe",
    floor: "Teatergatan",
    img: "https://via.placeholder.com/350x200?text=DJ+Schysst",
    social: {
      spotify: "https://open.spotify.com/artist/ARTIST_ID_SCHYSST",
      instagram: "dj_schysst",
    },
    track: "https://open.spotify.com/embed/track/TRACK_ID_SCHYSST",
    pressImage: "assets/press/dj-schysst.jpg",
    spotifyEmbed: "https://open.spotify.com/embed/artist/ARTIST_ID_SCHYSST",
  },
  {
    name: "Artistakt RÖDA RUMMET PLACEHOLDER",
    style: "Kort pauseffektakt.",
    desc: "Kort akt mellan DJs.",
    time: "00:55–01:10",
    genre: "Interlude",
    floor: "Röda rummet",
    img: "https://via.placeholder.com/350x200?text=Interlude",
    social: {
      spotify: "#",
      instagram: "#",
    },
    track: "#",
    pressImage: "assets/press/interlude.jpg",
    spotifyEmbed: "#",
  },
  {
    name: "Artistakt ÖVERE BAREN PLACEHOLDER",
    style: "Kort pauseffektakt.",
    desc: "Kort akt mellan DJs.",
    time: "01:00–01:15",
    genre: "Interlude",
    floor: "Övre baren",
    img: "https://via.placeholder.com/350x200?text=Interlude",
    social: {
      spotify: "#",
      instagram: "#",
    },
    track: "#",
    pressImage: "assets/press/interlude.jpg",
    spotifyEmbed: "#",
  },
  {
    name: "Artistakt Lilla London UTE PLACEHOLDER",
    style: "Kort pauseffektakt.",
    desc: "Kort akt mellan DJ (15min??)",
    time: "00:00–00:15",
    genre: "Interlude",
    floor: "Lilla London UTE",
    img: "https://via.placeholder.com/350x200?text=Interlude",
    social: {
      spotify: "#",
      instagram: "#",
    },
    track: "#",
    pressImage: "assets/press/interlude.jpg",
    spotifyEmbed: "#",
  },
  {
    name: "Inner Circle DJ #1 (TBD) PLACEHOLDER",
    style: "TBH",
    desc: "TBH",
    time: "23:00–00:00",
    genre: "TBH",
    floor: "TEATERGATAN",
    img: "https://via.placeholder.com/350x200?text=Interlude",
    social: {
      spotify: "#",
      instagram: "#",
    },
    track: "#",
    pressImage: "assets/press/interlude.jpg",
    spotifyEmbed: "#",
  },
  {
    name: "Inner Circle DJ #2 (TBD) PLACEHOLDER",
    style: "TBH",
    desc: "TBH",
    time: "02:15–03:00",
    genre: "TBH",
    floor: "TEATERGATAN",
    img: "https://via.placeholder.com/350x200?text=Interlude",
    social: {
      spotify: "#",
      instagram: "#",
    },
    track: "#",
    pressImage: "assets/press/interlude.jpg",
    spotifyEmbed: "#",
  },
  {
    name: "Artistakt TEATERGATAN PLACEHOLDER",
    style: "TBH",
    desc: "TBH",
    time: "02:00–02:15",
    genre: "TBH",
    floor: "TEATERGATAN",
    img: "https://via.placeholder.com/350x200?text=Interlude",
    social: {
      spotify: "#",
      instagram: "#",
    },
    track: "#",
    pressImage: "assets/press/interlude.jpg",
    spotifyEmbed: "#",
  },
];
